# Syntax for each header is [People_Who_Brought-Poeple_Who_Owe] or [People_Who_Brought] which defaults to split between all poeple
[Currency]
main = "£"
K = "£0.074"

[Em_Steve]
hot_dogs_sat = 35

[Em_Steve-Em_Steve_Pete]
flights = 666
car_park = 55
hot_dogs_sun = 21
lake_drinks_pancake = 21

[Steve-Steve_Pete]
monday_brekky_airport = 16

[Pete-Steve_Em_Pete]
spoons_brekky = 30

[Matt_Benny]
fuel = "K500"
shop_to_cabin = "K800" 
fireworks = "K2000"
farm_shop = "K1000"
dinner_shop_fri = "K1000"
pepperkaka = "K800"
saturday_dinner = "K1000"

[Matt-Matt_Em_Steve_Pete]
bus_x2 = "K500"
vehicular = "K500"
