# Syntax for each header is [People_Who_Brought-Poeple_Who_Owe] or [People_Who_Brought] which defaults to split between all poeple
[Currency]
main = "£"
K = "£0.074"

[Weights]
MattBenny = 2
EmSteve = 2
Pete = 1

[EmSteve]
hot_dogs_sat = 35

[EmSteve-EmSteve_Pete]
flights = 666
car_park = 55
hot_dogs_sun = 21
lake_drinks_pancake = 21
monday_brekky_airport = 16

[Pete-EmSteve_Pete]
spoons_brekky = 30

[MattBenny]
fuel = "K750"
shop_to_cabin = "K1966" 
fireworks = "K2796"
farm_shop = "K1000"
dinner_shop_fri = "K1174"
pepperkaken = "K995"

[MattBenny-Pete]
jam = "K187"

[MattBenny-EmSteve_Pete]
bus_x2 = "K374"
funicular = "K320"
