[Em_Steve]
river_boat_drinks = 20
breakfast_1st_day = 92
post_museum_coffee = 20
supermarket = 87
car_rental = 450
teifenthal_drinks = 34
heidelburg_lunch = 107
lidl = 26
bad_durkheim_drinks = 18
fuel = 53

[Bo_Rafe]
taxi_to_boat = 20
taxi_back_to_station = 13
tower_viewing = 43
coffee_hand_cheese = 31
museum = 42
ice_cream_bad_dirkheim = 11.9

[Giles_Sue]
airbnb = 851.04
flights = 1006.44
boat = 96.10
heidelburg_lunch_tip = 10
heidelburg_drinks = 23.20